#! /bin/bash
# -*- mode: Shell-script; -*-
# report on tags new in the last week to determine new recipe targets
RELDIR=$(dirname $0)
C_ORANGE='\033[0;33m'
C_GREEN='\033[0;32m'
C_BLUE='\033[0;34m'
C_RED='\033[0;31m'
C_NONE='\033[0m'

source $RELDIR/mtnsinit

offset=${1:-7}

secs=$(expr 60 \* 60)
secs=$(expr $secs \* 24)
secs=$(expr $secs \* $offset)
today=$(date -u -d now +%s)
last=$(expr $today - $secs) 

while read repoline; do
    h=$(echo ${repoline} | cut -f1 -d ' ')
    if test ! -d ${MTNSREPOS}/$h; then
        echo error: $h does not exist. run reposync first.
        continue
    fi

    while read tagline; do
        if test "x$tagline" == x; then
            continue;
        fi
        tagdate=$(echo $tagline | cut -f1-3 -d ' ')
        tagdate=$(date -u -d "$tagdate" +%s)
        if (( $tagdate < $last )); then
            continue 1
        fi
        #echo $h: $tagline
        tagvalue=$(echo $tagline | cut -f5 -d ' ')
        #echo TAGVALUE: $tagvalue
        outline=$(grep -e "$h" $RELDIR/versions.conf | grep -e "$tagvalue")
        status=$(echo $outline | cut -f1 -d ' ')
        if test x$status == xtodo; then
            printf "${C_ORANGE}todo${C_NONE} $(echo $outline | cut -f2-10 -d ' ')\n"
        elif test x$status == xdone; then
            printf "${C_GREEN}done${C_NONE} $(echo $outline | cut -f2-10 -d ' ')\n"
        elif test x$status == xskip; then
            printf "${C_BLUE}skip${C_NONE} $(echo $outline | cut -f2-10 -d ' ')\n"
        else
            printf "${C_RED}uhoh${C_NONE} $h $tagvalue\n"
        fi
    done < $MTNSCACHE/tags.$h
    
done < $RELDIR/repos.conf
